const actions = {
    ADD_CATEGORY: 'ADD_CATEGORY',
    SET_CATEGORY: 'SET_CATEGORY',
    GET_CATEGORY: 'GET_CATEGORY',
    ADD_SUB_CATEGORY: 'ADD_SUB_CATEGORY',
    SET_SUB_CATEGORY: 'SET_SUB_CATEGORY',
    GET_SUB_CATEGORY: 'GET_SUB_CATEGORY',
    GET_SUB_CATEGORY_BY_ID: 'GET_SUB_CATEGORY_BY_ID',
    SET_SUB_CATEGORY_BY_ID: 'SET_SUB_CATEGORY_BY_ID',
    SET_MENU_ITEM: 'SET_MENU_ITEM',
    UPDATE_MENU_ITEM: 'UPDATE_MENU_ITEM',
}
export default actions
